/**
 * Metrics event types
 * These power dashboards and KPIs
 */
export const METRIC_EVENT = {
  PAYMENT_CREATED: "PAYMENT_CREATED",
  AUTH_ATTEMPTED: "AUTH_ATTEMPTED",
  AUTH_SUCCEEDED: "AUTH_SUCCEEDED",
  AUTH_FAILED: "AUTH_FAILED",
  RETRY_TRIGGERED: "RETRY_TRIGGERED",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED"
};
